### ISSUE TITLE
关于cli2与cli3配置CDN时index.html有所不同，提出疑惑？

### ISSUE THREAD

**Issue by HannibalKcc** [HaoChuan9421/vue-cli3-optimization#1]
在cli2 与3中的index.html有些许不同。

2使用了script标签引入js；

3中不但使用了script标签引入js，还用了link标签预加载了一次。（而且link标签的as属性找了一下网上好像没有很多资料）

疑问：
请问2,3配置的不同是有意为之吗？
link标签预加载js有什么额外的好处吗？

**Comment by haochuan9421** [comment]
preload了解一下

**Comment by haochuan9421** [comment]
@HannibalKcc 
![image](https://user-images.githubusercontent.com/5093611/46932146-e9b2ca80-d080-11e8-92eb-c1f0bd35f00f.png)

https://github.com/philipwalton/webpack-esnext-boilerplate/issues/1
