### ISSUE TITLE
在vue.config.js配置加载cdn链接，还需要package.json里面声明？

### ISSUE THREAD

**Issue by io-o** [HaoChuan9421/vue-cli3-optimization#2]
`
  "dependencies": {
    "axios": "^0.18.0",
    "element-ui": "^2.4.8",
    "vue": "^2.5.17",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1"
  },
`

**Comment by haochuan9421** [comment]
现在调整了，对开发环境和生产环境进行了区分，你开发时还是会依赖npm包，build的时候就不依赖了，所以有必要

**Comment by io-o** [comment]
哦哦， 明白了， 非常感谢。
