### ISSUE TITLE
老哥，我使用你的vue.config.js配置，报错。

### ISSUE THREAD

**Issue by io-o** [HaoChuan9421/vue-cli3-optimization#3]
![image](https://user-images.githubusercontent.com/22197685/47005589-a5015f00-d166-11e8-9216-ab4020cd2a61.png)
vue-cli 3.0.4构建的ts版本，
我把你的vue.config.js直接拷贝过来。

**Comment by io-o** [comment]
。。。解决了， 需要清空下淘宝源。

**Comment by haochuan9421** [comment]
我刚才试了一下用ts模版的，并没有问题，你把vue.config.js拷贝过去之后，把`.npmrc`也拷贝过去，然后安装一些需要的包`npm i compression-webpack-plugin prerender-spa-plugin sass-resources-loader --save-dev`，注意我陪了sass相关的，那个里面需要style文件夹下面有那三个scss文件。你最好熟悉一下具体里面都是什么，实际开发，你要结合自己项目调整，我只是提供一个参考方案

**Comment by io-o** [comment]
![image](https://user-images.githubusercontent.com/22197685/47006661-01fe1480-d169-11e8-9b43-b562be68927d.png)
我安装好依赖，启动报这个错误。

**Comment by haochuan9421** [comment]
你这有毒吧，你用什么安装的？cnpm?yarn?npm?

**Comment by haochuan9421** [comment]
我说下一我的步骤算了：
1. 用`vue-cli3.0.4`创建项目，选择ts，用npm安装完依赖
2. 把`.npmrc`拷贝到跟目录
3. 执行`npm i compression-webpack-plugin prerender-spa-plugin sass-resources-loader --save-dev
4. 在src下创建style目录，并创建那三个文件
5. npm run serve

**Comment by io-o** [comment]
我用的npm， 之前指定了淘宝源， npm install 后报第一个错误， google后，清除了淘宝源，安装正常。 我用下你的方法试试。

**Comment by io-o** [comment]
可以啦， 非常感谢。
