### ISSUE TITLE
build后的文件，打开白屏，啥也没有，也没报错

### ISSUE THREAD

**Issue by io-o** [HaoChuan9421/vue-cli3-optimization#4]
生成的index.html，直接打开后白屏，
需要node服务器启动？

**Comment by haochuan9421** [comment]
你是直接使用的这个项目吗？有没有修改什么？

**Comment by io-o** [comment]
算是直接使用的， 把element-ui 库 换成了， iview的， 去除SASS，npm run serve能正常运行。

**Comment by haochuan9421** [comment]
你把项目上传到GitHub，然后回复一下仓库地址，可以帮你看一下

**Comment by io-o** [comment]
好的谢谢，只上传build之后的就可以把？

**Comment by haochuan9421** [comment]
传完整的呀，build之后的我怎么看的出来问题😂

**Comment by io-o** [comment]
。。。啥也没修改，重新build一次后 又好了😂😂😂😂， 想问下，这个路径问题，你是怎么解决的， 我build之后，都是绝对路径，需要手动修改成相对路径， 
```
 baseUrl: BASE_URL,
  outputDir: DIST_ROOT + BASE_URL,
  assetsDir: './static',
```

**Comment by haochuan9421** [comment]
![image](https://user-images.githubusercontent.com/5093611/47836368-feae8e00-dde2-11e8-9f5e-5cb0aab97be7.png)
这个改成`./dist`不就是相对路径了？

**Comment by io-o** [comment]
不行， 我试了， 你的build后的文件路径都是对的么？
我的index.html里路径都是错的
![image](https://user-images.githubusercontent.com/22197685/47837800-47b51100-dde8-11e8-9aec-1cedf9b57ec2.png)

![image](https://user-images.githubusercontent.com/22197685/47837838-661b0c80-dde8-11e8-8adf-89340a29d992.png)

**Comment by haochuan9421** [comment]
你这没错呀，`/static`是就绝对路径，你不要直接打开呀，需要在服务器环境下的，本地打开肯定不行

**Comment by io-o** [comment]
好了， 改了上面， 下面也要重新改。 多谢， 感觉问题太多了， cdn引入， 各种插件的方法属性全都null, 要一个一个改

**Comment by haochuan9421** [comment]
兄嘚~总感觉你哪里姿势不对，预渲染有坑，我可以理解，但是CDN基本是没啥坑的，如果你担心后面有坑，你就不要用预渲染了。

**Comment by io-o** [comment]
老哥， 解决了，都是iview的坑， 我决定换elment-ui了， 你可以在README.md加上这句话，使用iview时需要注意组件使用。
![image](https://user-images.githubusercontent.com/22197685/47839847-315e8380-ddef-11e8-86dc-89aca875fde8.png)

**Comment by haochuan9421** [comment]
你可以提一个PR
