### ISSUE TITLE
 Vue is not defined

### ISSUE THREAD

**Issue by jl1014171068** [HaoChuan9421/vue-cli3-optimization#8]
请问下大佬，为什么我这边按照你的走下来会报这个错。。。

**Comment by haochuan9421** [comment]
1. webpack 是否配置 externals 选项？
2. 不要删除 import Vue from 'vue'！
3. 是否加载了引入 vue.js 的 CDN 链接？

**Comment by jl1014171068** [comment]
![image](https://user-images.githubusercontent.com/12130044/49869125-63c9ba80-fe4a-11e8-8122-bd52db3a96ae.png)
![image](https://user-images.githubusercontent.com/12130044/49869133-6e844f80-fe4a-11e8-91e2-93bcebc4c0c9.png)

**Comment by haochuan9421** [comment]
你的index.html和我的仓库里的一样吗？里面有script的标签引入，检查一下控制台是否加载了vue.min.js

**Comment by jl1014171068** [comment]
![image](https://user-images.githubusercontent.com/12130044/49869507-84dedb00-fe4b-11e8-9d35-cf199238a512.png)

您的仓库没有index.html....我有去看您的cli2项目里面index。html没有加载script。。。

**Comment by haochuan9421** [comment]
在public目录下

**Comment by jl1014171068** [comment]
感谢您，解决了，速度快了太多了，这个问题我解决了两天了，vendor达到了10m.... -。-
